---
title: "Introduction to data wrangling, visualization, and analysis in Rstudio"
subtitle: "00 - introductions and overview"
author: "Jenny Bigman"
date: '05/12/22'
output:
  xaringan::moon_reader:
    css: ["default", ninjutsu, rladies-fonts]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
# Install and load pacman (library management package)
if (!require("pacman")) install.packages("pacman")

# Install and load required packages from CRAN ----
pacman::p_load(xaringan, knitr, here, install = FALSE)

knitr::opts_chunk$set(echo = F)

```

class: inverse

## Welcome! <br >
--
 
 **About me**  
NRC & NSF Postdoctoral Fellow, NOAA Alaska Fisheries Science Center, Seattle, WA

 _Previously:_  
 PhD from Simon Fraser University  
 MSc from Moss Landing Marine Labs  
 BSc from University of North Carolina Wilmington  

--

**Background**  
macroecology, life history theory, (comparative) ecophysiology, phylogenetic comparative methods, bayesian modeling

--

**Research interests**  
I bridge macroecology with fisheries science to understand physiological, ecological, and evolutionary patterns across fishes (and other vertebrates). I mostly think about how environmental variation elicits these patterns and how these patterns (and fish) will change in the future as our climate changes. I am especially interested in the effects of oxygen and temperature on the ecology and evolution of fishes (size, abundance, distribution, life histories)

--
<div class = "red">
I am not an expert in R or statistics -- I am an R user that <i> has experience </i>    with data wrangling, visualization, and analysis
</div>
---
class: center, middle, inverse

#You?
---

class: inverse

###This workshop will be an **introduction** to R

--

We will learn how to:
1. import a dataframe into R
2. examine and manipulate data 
3. preliminary plots for data exploration
4. begin analyzing data
5. edit ggplot themes to make a publication quality figure
6. seeking help and other resources

--

**We may not get through all of this. That is ok because your R journey does not end here. This is a beginner's course and there is much to learn (I am still learning new things everyday!). There are many online resources (how most people learn R, including myself), which we will go over at the end.**
---

class: inverse

##Timeline

Snacks; lunch at 1pm (after we finish)

Please feel free to leave if needed (I will plan for a few breaks)

Stickies -- this is your workshop! Speak up if do not understand

Helper
---

class: inverse

###Everyone should have R _and_  Rstudio downloaded and installed

--

This will be our first sticky note exercise: if you have successfully downloaded and installed R -and- Rstudio, please put a blue stick note on your laptop

---