---
title: "Introduction to data wrangling, visualization, and analysis in Rstudio"
subtitle: "01 - what is Rstudio?"
date: '05/12/22'
output:
  xaringan::moon_reader:
    css: ["default", ninjutsu, rladies-fonts]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

class: inverse

###What is Rstudio    
--

Rstudio is an interface to work with R  -- called an 'integrated development environment (IDE)'

--

###What is R  

--

R is a programming language _and_ software that interprets the language/code  

--

Will need to update R _and_ Rstudio periodically  

--

### How to update R and Rstudio  

--

To update Rstudio, go to 'Help > Check for Updates'  

To update R, go back to CRAN (where you downloaded R from) and download a new version  

Packages will need to be updated as well, go to Files/Plots/Packages/Help/Viewer pane > Packages, 'Update' at top (green circle with white arrow); alternatively, go to Tools > Check for Package Updates

---

class: inverse

##There are four 'panes' in Rstudio    


1. Source:

2. Console:

3. Environment/History:  

4. Files/Plots/Packages/Help/Viewer:

---

class: inverse

##There are four 'panes' in Rstudio    


1. Source: write and save code

2. Console:

3. Environment/History:  

4. Files/Plots/Packages/Help/Viewer: 

---

class: inverse

##There are four 'panes' in Rstudio    


1. Source: write and save code

2. Console: run code

3. Environment/History:  

4. Files/Plots/Packages/Help/Viewer: 

---

class: inverse

##There are four 'panes' in Rstudio    


1. Source: write and save code

2. Console: run code

3. Environment/History: shows objects in workspace (Environment) and your command history (History)  

4. Files/Plots/Packages/Help/Viewer 
---

class: inverse

##There are four 'panes' in Rstudio    


1. Source: write and save code

2. Console: run code

3. Environment/History: shows objects in workspace (Environment) and your command history (History)

4. Files/Plots/Packages/Help/Viewer: navigate to files/directories, view plots, install packages, get help

---

class:inverse

### Why R

--

R is great for reproducibility  

--

No pointing and clicking!  

--

R works on data of all shapes and sizes (and for the most part, types)  

--

R produces high-quality graphics  

--

Large, welcoming, helpful community  

--

Free, open source, cross-platform


--

##It is the standard in ecology/physiology
---

class: inverse, middle, center

#Ready? Let's go